version: "3.9"  
services:
  hwpcweb:
    build: 
      context: .
    image: hwpc-web
    container_name: hwpc-web-app
    environment:
      - PORT=${PORT}
      - PY_VERSION=${PY_VERSION}
    ports:
      - "443:443"
      - "80:80"
    # Once deployed, update healthcheck for AWS environment
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT}"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
