version: "3.9"  
services:
  hwpcweb:
    build: 
      context: .
    image: hwpc-web
    container_name: hwpc-web-app
    environment:
      - PORT=${PORT}
      - PY_VERSION=${PY_VERSION}
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
